### ISSUE TITLE
Entity - Visit

### ISSUE THREAD

**Issue by yzummy** [kevinschoonover/jeeves#20]
- [x] Visit ID
- [x] Users
- [ ] Orders
- [x] Waiter/Waitress Assigned
- [x] Arriving Time
- [x] Leaving Time
- [x] Transaction
- [x] Method of Payment (Split, altogether)

**Comment by christopher-o-toole** [comment]
Orders are not implemented yet still, see #14

**Comment by christopher-o-toole** [comment]
Currently holds one shift object, but perhaps multiple waiters/staff members may server one group in exceptional circumstances. Further investigation is warranted.

**Comment by kevinschoonover** [comment]
Closed in #35
